version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: shortcut-zone_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '1337:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
